### ISSUE TITLE
Project-Engagement: Create a Project Tracking Process

### ISSUE THREAD

**Issue by csmcallister** [GSA/MD-GitHub-Admin#3]
As a team member, I want us to agree upon the suite of tools and processes that we'll use to track projects so that our work is more organized, transparent, and replicable.

## Acceptance criteria
- [ ] Document in Team Drive outlining the engagement process
- [ ] Participation from everyone on the team
- [ ] Current projects retro-fit to the standards we develop
